#ifndef _TCOD_NOISE_DEFAULTS
#define _TCOD_NOISE_DEFAULTS

#define TCOD_NOISE_MAX_OCTAVES			128
#define TCOD_NOISE_MAX_DIMENSIONS		4
#define TCOD_NOISE_DEFAULT_HURST        0.5f
#define TCOD_NOISE_DEFAULT_LACUNARITY   2.0f

#endif /* _TCOD_NOISE_DEFAULTS */
